### PR TITLE
make strings with variables translatable

### PR DESCRIPTION
**Pull request by UB3RL33T**

### CODE REVIEW

**Comment by amenk** [comment]
@UB3RL33T Please add the German translations as well for those new strings.

**Review by amenk — APPROVED** [review]

**Comment by amenk** [comment]
@Popesites can you merge?

**Comment by Popesites** [comment]
merged!


Best regards,

*Conner Pope*
703-474-7206



This e-mail message is confidential and may be privileged or otherwise
protected by law.  If you are not the intended recipient, please: (1) reply
via e-mail to sender; (2) destroy this communication entirely, including
deletion of all associated text files from all individual and network
storage devices; and (3) refrain from copying or disseminating this
communication by any means whatsoever.

**Comment by amenk** [comment]
@Popesites 
Thanks for merging. Would you mind tagging a release as well? 

remark: You published your phone number :)

**Comment by Popesites** [comment]
Thanks for pointing that out, I deleted that bit ;) 

I'll create a release, we can edit up the title/description for it as we go.

**Pull request merged**
